In [1]:
import gym
import CustomGymEnvs
import torchgraphs as tg
import torch
import torch.nn as nn

from collections import OrderedDict

In [2]:
env = gym.make("FetchReachEnv-v0")

In [3]:
num_nodes = env.observation_space['observation_nodes'].shape[0]
num_edges = env.observation_space['observation_edges'].shape[0]

In [85]:
# g1 = tg.GraphBatch(
#     node_features=torch.FloatTensor(env.robot_graph.node_features),
#     edge_features=torch.FloatTensor(env.robot_graph.edge_features),
#     senders=torch.tensor(env.robot_graph.edges_from),
#     receivers=torch.tensor(env.robot_graph.edges_to),
#     global_features=torch.randn([1, 10]),
#     num_nodes_by_graph=torch.tensor([num_nodes]),
#     num_edges_by_graph=torch.tensor([num_edges])
# )

g1 = tg.Graph(
    node_features=torch.FloatTensor(env.robot_graph.node_features),
    edge_features=torch.FloatTensor(env.robot_graph.edge_features),
    senders=torch.tensor(env.robot_graph.edges_from),
    receivers=torch.tensor(env.robot_graph.edges_to),
    global_features=torch.randn([1, 10])
)

In [86]:
# g2 = tg.GraphBatch(
#     node_features=torch.FloatTensor(env.robot_graph.node_features),
#     edge_features=torch.FloatTensor(env.robot_graph.edge_features),
#     senders=torch.tensor(env.robot_graph.edges_from),
#     receivers=torch.tensor(env.robot_graph.edges_to),
#     global_features=torch.randn([1, 10]),
#     num_nodes_by_graph=torch.tensor([num_nodes]),
#     num_edges_by_graph=torch.tensor([num_edges])
# )

g2 = tg.Graph(
    node_features=torch.FloatTensor(env.robot_graph.node_features),
    edge_features=torch.FloatTensor(env.robot_graph.edge_features),
    senders=torch.tensor(env.robot_graph.edges_from),
    receivers=torch.tensor(env.robot_graph.edges_to),
    global_features=torch.randn([1, 10]),
)

In [6]:
dataloader = torch.utils.data.DataLoader([g1, g2], collate_fn=tg.GraphBatch.collate)

In [94]:
a = tg.GraphBatch.collate([g1, g2])

In [99]:
a.global_features = torch.randn([2, 10])

In [101]:
a.global_features.shape

torch.Size([2, 10])

In [79]:
class QNetwork(nn.Module):
    def __init__(self, num_node_features, num_edge_features, num_actions):
        # For the action value function, we consider the action as the graph's global features
        super(QNetwork, self).__init__()
        
        self.edge1 = tg.EdgeLinear(256,
                                   edge_features=num_edge_features,
                                   sender_features=num_node_features,
                                   receiver_features=num_node_features,
                                   global_features=num_actions)
        self.edge_relu1 = tg.EdgeReLU()

        self.node1 = tg.NodeLinear(256,
                                   node_features=num_node_features,
                                   incoming_features=256,
                                   global_features=num_actions,
                                   aggregation='avg')
        self.node_relu1 = tg.NodeReLU()

        self.global1 = tg.GlobalLinear(int(num_actions / 2),
                                       node_features=256,
                                       edge_features=256,
                                       global_features=num_actions,
                                       aggregation='avg')
        self.global_relu = tg.GlobalReLU()

        self.edge2 = tg.EdgeLinear(128,
                                   edge_features=256,
                                   sender_features=256,
                                   receiver_features=256,
                                   global_features=int(num_actions / 2))
        self.edge_relu2 = tg.EdgeReLU()

        self.node2 = tg.NodeLinear(128,
                                   node_features=256,
                                   incoming_features=128,
                                   global_features=int(num_actions / 2),
                                   aggregation='avg')
        self.node_relu2 = tg.NodeReLU()

        self.global_output = tg.GlobalLinear(1,
                                             node_features=128,
                                             edge_features=128,
                                             global_features=int(num_actions / 2),
                                             aggregation='avg')

    def forward(self, g):
        print(g)
        g = self.edge_relu1(self.edge1(g))
        print(g)
        g = self.node_relu1(self.node1(g))
        print(g)
        g = self.global_relu(self.global1(g))
        print(g)
        g = self.edge_relu2(self.edge2(g))
        print(g)
        g = self.node_relu2(self.node2(g))
        print(g)
        return self.global_output(g)

In [80]:
q = QNetwork(g1.node_features_shape[0], g1.edge_features_shape[0], 10)

In [83]:
# q(tg.GraphBatch.collate((g1, g2)))
q(g1).global_features

GraphBatch(#1, n=tensor([28]), e=tensor([27]), n_shape=torch.Size([14]), e_shape=torch.Size([10]), g_shape=torch.Size([10]))
GraphBatch(#1, n=tensor([28]), e=tensor([27]), n_shape=torch.Size([14]), e_shape=torch.Size([256]), g_shape=torch.Size([10]))
GraphBatch(#1, n=tensor([28]), e=tensor([27]), n_shape=torch.Size([256]), e_shape=torch.Size([256]), g_shape=torch.Size([10]))
GraphBatch(#1, n=tensor([28]), e=tensor([27]), n_shape=torch.Size([256]), e_shape=torch.Size([256]), g_shape=torch.Size([5]))
GraphBatch(#1, n=tensor([28]), e=tensor([27]), n_shape=torch.Size([256]), e_shape=torch.Size([128]), g_shape=torch.Size([5]))
GraphBatch(#1, n=tensor([28]), e=tensor([27]), n_shape=torch.Size([128]), e_shape=torch.Size([128]), g_shape=torch.Size([5]))


tensor([[1.7000]], grad_fn=<AddBackward0>)

In [26]:
rb = ReplayMemory(30, 0)

for _ in range(20):
    g = tg.Graph(
        node_features=torch.tensor(env.robot_graph.node_features),
        edge_features=torch.tensor(env.robot_graph.edge_features),
        senders=torch.tensor(env.robot_graph.edges_from),
        receivers=torch.tensor(env.robot_graph.edges_to),
    )
    rb.push(g, 1, 2, g, False)

In [6]:
torch.cat((torch.rand([256, 6]), torch.rand([256, 1])), 1).shape

torch.Size([256, 7])

In [1]:
a = {'a': 1, 'b': 2, 'c': 3}

In [6]:
import numpy as np
np.array(list(a.values())) / 2

array([0.5, 1. , 1.5])

In [1]:
import numpy as np

In [17]:
arr = np.empty([0, 5])

In [20]:
arr2 = np.append(arr, [[0,1,2,3,4]], axis=0)

In [22]:
np.append(arr2, np.arange(5, 10).reshape(1, 5), axis=0)

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [31]:
import pandas as pd

pd.read_csv('/home/mehran/Documents/SAC_GCN/Data/FetchReachEnv-v0/standard/seed0/eval.csv')

num_episodes  num_steps  num_updates  eval_reward
0          10.0      500.0        243.0   -10.249750
1          20.0     1000.0        743.0    -6.389949
2          30.0     1500.0       1243.0    -8.711387
3          40.0     2000.0       1743.0    -6.880497
4          50.0     2500.0       2243.0    -7.790122
5          60.0     3000.0       2743.0    -7.270830
6          70.0     3500.0       3243.0    -6.690151
7          80.0     4000.0       3743.0    -7.699853

In [2]:
d = [1,2,3,4]
d += [4,5,6,7]

In [1]:
import torch

In [3]:
model = torch.load('Data/HalfCheetahEnv-v0/standard/seed0/model')

In [8]:
model['policy_state_dict']['mean_linear.W_global'].shape

torch.Size([6, 128])

In [1]:
import numpy as np

In [10]:
np.linspace(1, 100, 100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [5]:
a = np.array([1,2,3])
b = np.arange(5)

In [16]:
np.concatenate([a, b])

array([1, 2, 3, 0, 1, 2, 3, 4])

In [21]:
import os
from pathlib import Path
os.path.abspath(__file__)

NameError: name '__file__' is not defined

In [3]:
import numpy as np

In [4]:
np.zeros([13])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [1]:
a = {'b':2, 'a':1, 'c':0}

In [6]:
isinstance([1,2,3,4], list)

True

In [8]:
a['d'] = None

In [10]:
a['d']